[ADD] 제품 상세 페이지
wecode-bootcamp-korea/37-1st-WePleats-backend pull request #11
Opened 2022-09-25 06:41 UTC by pienkk

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 상세 페이지 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-09-27 06:57 UTC, lordmyshepherd requested changes

2022-09-27 06:57 UTC, lordmyshepherd commented on controllers/productController.js
> +const detailProduct = asyncWrap(async (req, res) => {
함수명은 동사로 만들어주세요~
`detailProduct` -> `getProduct`

2022-09-27 06:57 UTC, lordmyshepherd commented on controllers/productController.js
> +    return res.status(200).json({ product: detail, review: review})
가독성을 위해서, 간격을 추가해주세요.

```suggestion
    const { productId } = req.params;
    
    if ( !productId ) {
        const err = new Error("KEY_ERROR");
        err.statusCode = 400;
        throw err;
    }
    
    const [ product, review ] = await productService.getProduct(productId);
    
    return res.status(200).json({ product: product, review: review})
```

2022-09-27 06:57 UTC, lordmyshepherd commented on services/productService.js
> +    const detailProduct = await productDao.getProductDetail( productId );
productDao의 `getProductById` 함수와 `getProductDetail` 함수가 분리되어 있을 필요가 있는지 고민해보면 좋을 것 같습니다.
두 함수 모두 productId를 전달받아서 product 정보를 반환하는 역할을 하고 있기 때문에, 하나로 합쳐서 사용할 수 있겠습니다.

```suggestion
    const product = await productDao.getProductById( productId );
    if ( !product ) {
        const err = new Error("INVALID_PRODUCT");
        err.statusCode = 406;
        throw err;
    }
```

2022-09-27 06:57 UTC, lordmyshepherd commented on services/productService.js
> +    const productImage = await productDao.getProductImage( productId );
반환되는 값이 여러개인지 여부를 반드시 코드에 명시해주는 것이 좋습니다.
아래와 같이 배열로 반환되는 데이터는 복수로 변수명을 설정해주세요~
```suggestion
    const reviews = await reviewDao.getReviewByProduct( productId );
    const images = await productDao.getProductImage( productId );
```

2022-09-27 09:03 UTC, pienkk commented on services/productService.js
> +    const productImage = await productDao.getProductImage( productId );
넵 수정 완료했습니다!

2022-09-28 06:55 UTC, Jon9Beom commented
LGTM 👍

2022-09-28 06:55 UTC, merged